// Automatically generated by Interoptopus.

using System;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using My.Company;

namespace My.Company
{

    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    public partial struct ByteArr
    {
